### ISSUE TITLE
generate DOS images/archives on github

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-otherdos#3]
http://manmrk.net/tutorials/bootdisk/index.htm
This is a collection of various DOSes.
We need to support installing from it.

**Comment by jschwartzenberg** [comment]
I think supporting these might be useful, but I typically those bootdisks provide a very incomplete environment. Some of the DOSes there are also listed in these archives:
https://ia801604.us.archive.org/view_archive.php?archive=/12/items/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip
https://ia803207.us.archive.org/view_archive.php?archive=/26/items/tosec_fw_os/TOSEC%20-%20Operating%20Systems/IBM%20PC%20Compatibles%20-%20Operating%20Systems%20-%20%5BRAW%5D%20%28TOSEC-v2018-11-15_CM%29.zip
https://ia803207.us.archive.org/view_archive.php?archive=/26/items/tosec_fw_os/TOSEC%20-%20Operating%20Systems/IBM%20PC%20Compatibles%20-%20Operating%20Systems%20-%20%5BIMA%5D%20%28TOSEC-v2018-11-15_CM%29.zip
https://ia803207.us.archive.org/view_archive.php?archive=/26/items/tosec_fw_os/TOSEC%20-%20Operating%20Systems/IBM%20PC%20Compatibles%20-%20Operating%20Systems%20-%20%5BIMG%5D%20%28TOSEC-v2018-11-15_CM%29.zip

Note that while the URLs end in `.zip` they actually list their contents and allow individual file downloads. (The scripts similarly download individual files out of these archives.)

I would thus suggest a full installation from the above sources is preferable. At least for MS-DOS I expect the existing installation routine in Python will cope with many MS-DOS versions without changes. Their names and URLs would just need to be added to the list.

**Comment by stsp** [comment]
Aren't there complete "enough"
installations of ms-dos in bootdisk
site?
Replicating the MS-DOS installer
in python with msexpand, is far
from the best idea.

**Comment by jschwartzenberg** [comment]
Define "enough" :) I think in most cases they will work, but in some case binaries like `choice` are missing which can introduce compatibility issues with batch files. The Python script implements the exact steps that Microsoft described in KB117245, so this is a documented approach.

I'm curious if you have other ideas. Running the actual installers for these is non-trivial with just dosemu although it may be possible to script their execution to install to a disk image and then pull the files out of the resulting temporary installation image.

**Comment by stsp** [comment]
We can do it differently.
How about this approach:
have the online installer in the
separate repo, and run it on
github to generate the DOS
images as a build artefacts.
Then local installers will
D/L the pre-built images from
github.

Then the online installers will
depend on msexpand, but
dosemu2 won't depend/suggest
them. So dosemu2 will only be
concerned with the very light-weight
installers. The heavy-weight tasks
are all done on github,

Of course we need to call to
@andrewbird for a github
expertise. :)

**Comment by stsp** [comment]
@stuaxo you are the python coder,
please join this project. :)

**Comment by stuaxo** [comment]
I am lurking and keeping up with these tickets ... but at the moment overloaded with python for work, and have python for upcoming Libre Graphics Meeting TODO.

I can't find info on the KB, above - but assume that's the one where they put together a system disk from an older DOS version, for inclusion in one of the older Windows ?

If it's the same one, I remember having a moment of realising "oh, Microsoft are creating DOS distros in the same way as all the ones I hadn't thought of as legitimate".

It's certainly doable, would it be a single FAT image per pre-installed DOS ?

**Comment by stsp** [comment]
> I am lurking and keeping up with these tickets

No, you are not subscribed to this
project AFAICS.

> It's certainly doable, would it be a single FAT image per pre-installed DOS ?

I am more thinking of just a zip file.
We don't need the real fat images.
There is already the script that mimics
an ms installer. All we need to do is
to make it standalone and put into
another repo. And in this repo only
D/L the pre-build archive from github
and extract it.

**Comment by jschwartzenberg** [comment]
> We can do it differently.
> How about this approach:
> have the online installer in the
> separate repo, and run it on
> github to generate the DOS
> images as a build artefacts.

Then we distribute it ourselves. The current trick relies on the fact that archive.org can do the distribution legally through its library exemption.

> I can't find info on the KB, above - but assume that's the one where they put together a system disk from an older DOS version, for inclusion in one of the older Windows ?

No it describes what their MS-DOS installer does and how to replicate that, here is the article:
http://web.archive.org/web/20150120032702/http://support.microsoft.com:80/kb/117245

**Comment by stsp** [comment]
No, we do not distribute it ourselves.
Its still distributed by some archive from
which we d/l.
Its just that the install procedure is split
into 2 parts. These urls will not be available
for others, and in fact they will be entirely
useless for anything else, as this is not
a bootable image.

**Comment by stsp** [comment]
Also you can of course do the entire
thing locally. Having that also on github,
is just suggested for a help to those
who doesnt want to install those
"dos generator" packages.

**Comment by stsp** [comment]
So there can be a generic solution:
we can turn this repo into a "dos generator"
that just provides the different DOSes
in a zipped form. And for dosemu2 there
should just be 1 script that unzips everything
that is currently available and installs
to proper dirs.

**Comment by stsp** [comment]
Or another split seems more practical:
there are some "pre-cooked" DOSes,
like svardos and opendos. Those can
be installed directly, as they are now,
This doesn't require any DOS-specific
tools (msexpand) and procedures (KB).
The rest (currently only MS-DOS) can
be moved to the "dos generators" that
can run either locally or on github.
The main installer should have its
menu removed, and it should grab all
the "directly available" DOSes, and
also look for whatever is available
from generators. This is mostly like
getting the (now removed)
`dosemu-downloaddos -l` back in.

**Comment by stsp** [comment]
This looks like the most practical
approach, as this way we can even
now just remove the msdos script
from here and remove menu, and
still have svardos and opendos
working. So the "generators" can
be added later.
