### ISSUE TITLE
7z dep is not listed

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-otherdos#7]
7z dep is not listed in deb/rpm recipes.
Its possible to add, but how about using
the more convenient tools, like rpm2cpio?

**Comment by jschwartzenberg** [comment]
It depends on which distro what is more convenient. I expect `rpm2cpio` to be available on RHEL/Fedora/OpenSUSE only whereas on most other distros it would need to be installed. The chances that someone has 7zip installed on those distros is higher. The best solution would seem a Python implementation if one is available.

**Comment by stsp** [comment]
rpm2cpio is there in ubuntu too.
I guess you can indeed use python's
unpacker after using rpm2cpio.
What do you think?

**Comment by jschwartzenberg** [comment]
> rpm2cpio is there in ubuntu too.

It's in the repository, but it usually is not installed as RPMs are not too common on Ubuntu. We can just add a dependency to it though.



> I guess you can indeed use python's
> unpacker after using rpm2cpio.
> What do you think?

After extracting the RPM we end up with an `hdimage`. To extract files from it, `mcopy` from `mtools` is used. I think I searched around for a Python implementation to handle that, but could not find one.

Reimplementing just the 7zip steps in Python will be easier I think.

**Comment by stsp** [comment]
> Reimplementing just the 7zip steps in Python will be easier I think.

Yes, that's what I mean.
But I think you will need to use rpm2cpio
first, as you probably can't work with rpm
directly from python.

**Comment by jschwartzenberg** [comment]
There's this library: https://pypi.org/project/python-libarchive/
I'm seeing some suggestions it might already be possible to use it with the CPIO part of an RPM directly.

**Comment by stsp** [comment]
If you can get it to work w/o both
7z and rpm2cpio - great. :)

**Comment by jschwartzenberg** [comment]
My package manager didn't actually offer that library, but this one instead:
https://pypi.org/project/libarchive-c/ 

No external tools are needed for this anymore. It seems it should also be possible to drop the requirement on using a temporary directory and do everything in-memory.

**Comment by stsp** [comment]
That looks cool.
Don't forget to update deps with PR.

**Comment by jschwartzenberg** [comment]
Seems whatever Python provides on `stdin` is not seekable (in contrast to other tools), so a temp file is needed.



>  Don't forget to update deps with PR.

Good point, I just took care of that! I'll create the PR now.
